[package]
name = "lc3-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "lc3-vm"
path = "src/lc3.rs"

[dependencies]
bitflags = "2.5.0"
